[package]
name = "kohonen" # the name of the package
version = "0.0.1"    # the current version, obeying semver
authors = ["John C McAlpine <christophermcalpine@gmail.com>"]
[dependencies]
palette = "*"
clap = "*"
rayon = "*"
rand = "*"
